# Generated by Django 4.1.7 on 2023-03-11 07:50

from django.db import migrations, models
import music_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_rename_votest_to_skip_room_votes_to_skip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='quest_can_pause',
            new_name='guest_can_pause',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music_api.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
