# Generated by Django 4.1.7 on 2023-03-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_rename_quest_can_pause_room_guest_can_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
